test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: raspberry_cook
  encoding: utf8
  username: raspberry_cook
  password: secret
  host:  localhost
  pool: 5
  timeout: 5000